<?php
return array(
'smtp'=>'smtp',
'web_mail_server'=>'frervsc',
'web_order_lock'=>'订单锁定时间(天)',
'web_order_close'=>'订单自动关闭原因444',
'web_login_verify'=>'0',
'web_check_product'=>'1',
'web_qq'=>'888888888',
'web_contact'=>'0858-2186567',
'web_service_time'=>'周一至周五9：00-17：30',
'web_allowed_reg'=>'0',
'web_reg_verify'=>'1',
'web_url'=>'http://www.boilqiao.cn/',
'web_record'=>'黔ICP备14003344号',
'web_footer'=>'版权所有：西南盘兴电子商务有限公司&lt;br&gt;
技术支持：贵州博益科技发展有限公司',
'order_lock'=>'',
'web_close_why'=>'网站维护当中,暂停访问',
'web_open'=>'1',
'web_description'=>'提供最新的行业资讯,矿用物资供应发布,矿用物资采购信息发布,涉安产品认证，杜绝假冒产品',
'web_keywords'=>'提供最新的行业资讯,矿用物资供应发布,矿用物资采购信息发布,涉安产品认证，杜绝假冒产品',
'web_name'=>'西南盘兴矿用物资电子商务服务平台',
'web_mail_acc'=>'smtp.qq.com',
'web_mail_pas'=>'12134566',
'web_mail_port'=>'25',
);
?>